name: TelegaBot .NET build + deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies 
      run: dotnet restore  # Обновление/установка зависимостей проекта

    - name: Build
      run: dotnet build --no-restore # Сборка проекта (без неявного восстановления)
      
    - name: Dotnet Publish
      run: dotnet publish -c Release -o deploy  # Публикация приложения в папку deploy

    - name: Test
      run: dotnet test
  
