name: TelegaBot .NET build + deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies 
      run: dotnet restore  # Обновление/установка зависимостей проекта

    - name: Build
      run: dotnet build --no-restore # Сборка проекта (без неявного восстановления)
      
    - name: Dotnet Publish
      run: dotnet publish -c Release -o deploy  # Публикация приложения в папку deploy

    - name: Run ssh comand 0
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo chown -R admin:www /home/www
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    env:
        CI: true

      
